// react-app/src/components/big-item/big-item.js
import './big-item.css';
import React from 'react';
import image from './hot-tasty-pizza.jpg'

export default class BigItem extends React.Component {
    render() {
        return (
            <div>
                <div>
                    <img src={image} alt="big item" width="1500px" height='900px' />
                </div>
                <div className="credits">
                    Graphical components credits:
                    <a href="https://www.freepik.com/photos/pizza-table">Pizza table photo created by Racool_studio - www.freepik.com</a>
                </div>
            </div>
        );
    }
}

// angular-app/src/app/components/big-item/big-item.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-big-item',
  templateUrl: './big-item.component.html',
  styleUrls: ['./big-item.component.css']
})
export class BigItemComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div>
    <img src="../../../assets/hot-tasty-pizza.jpg" alt="big item" width="1500px" height='900px'>
    <div class="credits">
        Graphical components credits:
        <a href="https://www.freepik.com/photos/pizza-table">Pizza table photo created by Racool_studio - www.freepik.com</a>
    </div>
</div>
