// angular-app/src/app/components/factory-test-item/factory-test-item.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-factory-test-item',
  templateUrl: './factory-test-item.component.html',
  styleUrls: ['./factory-test-item.component.css'],
  inputs: ['componentData']
})
export class FactoryTestItemComponent implements OnInit {

  constructor() { }

  componentData: {textContent?: string, graphicContent?: string} = {};
  textContent: string = '';
  graphicContent: string = '';

  ngOnInit(): void {
    if(this.componentData.textContent) this.textContent = this.componentData.textContent;
    if(this.componentData.graphicContent) this.graphicContent = this.componentData.graphicContent;
  }

}

<div>
    <p *ngIf="textContent">{{textContent}}</p>
    <img *ngIf="graphicContent" [src]="graphicContent" alt="graphic">
</div>

// react-app/src/components/factory-test-item/factory-test-item.js
import './factory-test-item.css';
import React from 'react';
import pizza from './hot-tasty-pizza.jpg'
import blue from './blue-graphic.png'

export default class FactoryTestItem extends React.Component {

    render() {
        return (
            <div>
                {this.props.componentData.textContent ? <p>{this.props.componentData.textContent}</p> : null}
                {(this.props.componentData.graphicContent && this.props.componentData.graphicContent==='./hot-tasty-pizza.jpg') ? <img src={pizza} alt="graphic" />: null}
                {(this.props.componentData.graphicContent && this.props.componentData.graphicContent==='./blue-graphic.png') ? <img src={blue} alt="graphic" />: null}
            </div>
        );
    }
}
