// angular-app/src/app/components/to-do-list/to-do-list.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';

@Component({
  selector: 'app-to-do-list',
  templateUrl: './to-do-list.component.html',
  styleUrls: ['./to-do-list.component.css']
})
export class ToDoListComponent implements OnInit {

  constructor() { }

  toDoItems: Array<string> = [];
  itemToAdd = new FormControl('');

  addItem() {
    this.toDoItems.push(this.itemToAdd.value)
    this.itemToAdd.setValue('');
  }

  removeItem(index: number) {
    this.toDoItems.splice(index,1)
  }

  ngOnInit(): void {
  }

}

<div class="form">
    <input class="new-item-input" type="text" placeholder="Type task name..." [formControl]="itemToAdd" (keyup.enter)="addItem()">
    <button class="new-item-button" (click)="addItem()">add item</button>    
</div>
<div *ngIf="toDoItems.length>0; else noItems">
    <div class="item-container" *ngFor="let item of toDoItems; let i = index">
        <app-to-do-list-item [item]="item"></app-to-do-list-item>
        <button class="remove-item-button" (click)="removeItem(i)">x</button>
    </div>
</div>
<ng-template #noItems>
    <div class="noItems">
        Add the first item using form above.
    </div>
</ng-template>

// react-app/src/components/to-do-list/to-do-list.js
import './to-do-list.css';
import React from 'react';
import ToDoListItem from '../to-do-list-item/to-do-list-item';

export default class ToDoList extends React.Component {

    constructor(props){
        super(props);
        this.state = {
            itemToAdd: "",
            toDoItems: []
        }
    }

    addItem = () => {
        this.state.toDoItems.push(this.state.itemToAdd);
        this.setState({ itemToAdd: '' });
    }

    removeItem = (index) => {
        this.state.toDoItems.splice(index,1)
        this.setState({toDoItems: this.state.toDoItems})
    }

    handleInputChange = (event) => {
        this.setState({itemToAdd: event.target.value})
    }

    render() {

        const items = this.state.toDoItems.length > 0 ? this.state.toDoItems.map((item, index) => {
            return  <div className="item-container" key={index}>
                        <ToDoListItem item={item}/>
                        <button className="remove-item-button" onClick={() => this.removeItem(index)}>x</button>
                    </div>
        }): <div className="noItems">
                Add the first item using form above.
            </div>

        return (
            <div>
                <div className="form">
                    <input className="new-item-input" type="text" placeholder="Type task name..." value={this.state.itemToAdd} onChange={this.handleInputChange}></input>
                    <button className="new-item-button" onClick={this.addItem}>add item</button>    
                </div>
                <div>{items}</div>
            </div>
        );
    }
}
